language: java
jdk:
    - oraclejdk8
    - oraclejdk7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pandoc

before_script:
    - cd ontologizer.parent

script:
    - mvn package -B

env:
  global:
  - secure: mlPpfQG9RuayWWXLt1tdEI4nb9ElObenj1QDfJ8qGxEqGleout8RE9cIxArB3WJ8jih/9lM3mkUm0y3cMMsf+SGRkfkWLO+YmVHqMslC0dwd3CqPMFjYPSJh7qsxaJC3b0RrZXujlXkwgDP16Yy/+h9RqAQwuTc3AtWepcLEZp0=
  - secure: viZg+Dmh8k1acvKYBf5yzDdTClekE5fqx84CttWZnljQlwVWbfJEqjSvWoyAvI07UosY69y3vJ5VKjIViDcz1N36LjcV+sxnWIfSwfTa6bCWeYS03cERlKQB6QJPR+RR/UFhloJy5XQyaLzC1TdVQTH4A01OV49uN8uUKjh7hyk=

# FIXME: Use deploy
after_success:
    - cd ontologizer.cmdline/target
    - java -version
    - java -version 2>&1 | awk '/version/{print $NF}'
    - \[\[ $(java -version 2>&1 | awk '/version/{print $NF}') =~ "1.7" \]\] && ../../deploy
